import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, Lock } from 'lucide-react';

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------
const SECTIONS = [
  {
    id: 'info-we-collect',
    title: '1. Information We Collect',
    content: `We collect information you provide directly to us and information generated by your use of the Service.

Account Information. When you register, we collect your name, email address, password (hashed), and date of birth for age verification. You may optionally provide a profile photo and bio.

Profile & Goal Data. Any bucket list goals, interests, or biographical information you choose to share on your profile, including completion photos and notes.

Usage Data. We collect information about how you use DreamLink, including the features you access, pages you view, searches you perform, matches you make, and messages you send. This includes device information (device type, OS, browser), IP address, referring URLs, and timestamps.

Location Information. With your permission, we collect approximate location data to show you users and goals nearby. You can disable location sharing at any time in your device settings. We do not store your precise GPS coordinates — only a generalised area.

Communications. If you contact our support team, we retain the content of those communications.

Payment Information. If you subscribe to a paid plan, payment details (card number, billing address) are collected and stored by our payment processor, Stripe. DreamLink only receives a token, last four digits, and card type — we never store full card details.`,
  },
  {
    id: 'how-we-use',
    title: '2. How We Use Your Information',
    content: `We use the information we collect to:

• Provide, maintain, and improve the DreamLink Service
• Create and manage your account
• Match you with other users based on shared bucket list goals
• Personalise your discovery feed and recommendations
• Send you transactional emails (account confirmation, password reset, match notifications)
• Send you marketing communications if you have opted in (you can opt out at any time)
• Process payments and manage subscriptions
• Monitor and analyse usage patterns to improve the Service
• Detect and prevent fraud, abuse, or security incidents
• Comply with legal obligations

Legal Basis (for EU/UK users). We process your personal data on the basis of: (a) performance of a contract (to provide the Service); (b) legitimate interests (security, fraud prevention, product improvement); (c) consent (location, marketing emails); and (d) legal obligation.`,
  },
  {
    id: 'sharing',
    title: '3. Information Sharing',
    content: `We do not sell your personal data. We do not rent or trade your information with third parties for their own marketing purposes.

We share information only in the following circumstances:

With Other Users. Profile information you mark as public — including your name, photo, bio, and goals — is visible to other DreamLink users. Messages are shared only with the matched user.

Service Providers. We share data with trusted vendors who help us operate the Service, including:
  • Supabase — database hosting and authentication
  • Stripe — payment processing
  • Resend — transactional email delivery
  • Sentry — error tracking (anonymised)

These vendors are contractually obligated to use your data only for the services they provide to us and to protect it appropriately.

Legal Requirements. We may disclose information if required by law, court order, or governmental authority, or if we believe disclosure is necessary to prevent harm or protect rights.

Business Transfers. If DreamLink is involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction. We will notify you via email and/or in-app notice before your information is transferred and becomes subject to a different privacy policy.`,
  },
  {
    id: 'storage-security',
    title: '4. Data Storage & Security',
    content: `Storage. Your data is stored in Supabase-managed PostgreSQL databases hosted on AWS infrastructure in the United States. If you are located in the EU or UK, your data may be transferred to the US under standard contractual clauses approved by the European Commission.

Encryption. All data in transit is encrypted using TLS 1.2 or higher. Sensitive data at rest (passwords, payment tokens) is encrypted using AES-256.

Access Controls. Database access is restricted by row-level security (RLS) policies. Only you — and DreamLink administrators for support purposes — can access your private data.

Security Measures. We implement industry-standard security practices including regular penetration testing, dependency vulnerability scanning, and audit logging.

No System Is Perfect. While we take security seriously, no method of transmission or storage is 100% secure. We cannot guarantee absolute security of your data. In the event of a security breach that affects your personal information, we will notify you as required by applicable law.`,
  },
  {
    id: 'your-rights',
    title: '5. Your Rights',
    content: `You have the following rights regarding your personal data:

Access. You can view most of your personal data directly in the app. You may request a full copy of your data by emailing support@dreamlink.app.

Correction. You can update your profile information at any time from the Edit Profile screen.

Deletion. You can delete your account from the app Settings. Account deletion removes your profile, goals, messages, and match history within 30 days. Some data may be retained for legal or fraud-prevention purposes.

Data Export. You can export your bucket list as a PDF (Premium+ feature). For a full data export, email support@dreamlink.app.

Opt-Out of Marketing. You can unsubscribe from marketing emails via the unsubscribe link in any email or by updating your notification preferences in the app.

Restrict Processing (EU/UK). You may request that we restrict processing of your data in certain circumstances. Contact support@dreamlink.app to submit a request.

Portability (EU/UK). You have the right to receive your personal data in a structured, commonly used, machine-readable format.

Complaints (EU/UK). If you believe we have violated your data protection rights, you have the right to lodge a complaint with your local supervisory authority.

We will respond to verified requests within 30 days.`,
  },
  {
    id: 'cookies',
    title: '6. Cookies & Tracking',
    content: `DreamLink uses cookies and similar tracking technologies to:

• Keep you logged in (session cookies)
• Remember your preferences
• Analyse Service usage (analytics)
• Prevent fraud

Essential Cookies. Required for the Service to function. Cannot be disabled.

Analytics Cookies. Help us understand how users interact with the Service so we can improve it. You can opt out through your browser settings.

We do not use advertising cookies or sell data to advertising networks. We do not use third-party tracking pixels.

You can control cookies through your browser settings, but disabling essential cookies may prevent parts of the Service from working correctly.`,
  },
  {
    id: 'childrens-privacy',
    title: "7. Children's Privacy",
    content: `DreamLink is not directed at children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe a child under 13 has provided us with personal information, please contact us at support@dreamlink.app and we will delete the information.

Users between 13 and 17 may access limited features of the Service (such as browsing public content) but cannot create an account or access social features. Full account registration and all social features require users to be 18 or older.

If we discover that a user is under 18 and has created a full account, we will suspend the account and delete associated personal data.`,
  },
  {
    id: 'contact',
    title: '8. Contact & Questions',
    content: `If you have questions, concerns, or requests regarding this Privacy Policy or how we handle your data, please contact our Privacy team:

DreamLink Inc.
Email: support@dreamlink.app
Website: dreamlink.app/contact

For EU/UK data subjects, you may also contact our representative by emailing privacy@dreamlink.app.

We aim to respond to all privacy requests within 30 days.`,
  },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-orange-50 via-white to-white">
      {/* Sticky nav */}
      <div className="sticky top-0 z-10 bg-white/80 backdrop-blur-md border-b border-orange-100">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 text-orange-500 hover:text-orange-600 font-semibold transition-colors">
            <ArrowLeft className="w-4 h-4" />
            DreamLink
          </Link>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-14">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="mb-10"
        >
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-xl bg-orange-100 flex items-center justify-center">
              <Lock className="w-5 h-5 text-orange-500" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Privacy Policy</h1>
              <p className="text-sm text-gray-400 mt-0.5">Last updated: June 2026 · DreamLink Inc.</p>
            </div>
          </div>
          <div className="bg-orange-50 border border-orange-200 rounded-xl p-4 text-sm text-orange-800 leading-relaxed">
            <strong>TL;DR:</strong> We collect only what we need to run DreamLink, we do not sell your data, and you can delete your account at any time. Read on for the full details.
          </div>
        </motion.div>

        {/* Table of contents */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
          className="bg-white rounded-2xl border border-orange-100 shadow-sm p-6 mb-10"
        >
          <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-3">Contents</h2>
          <ul className="space-y-1.5">
            {SECTIONS.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-sm text-orange-600 hover:text-orange-700 hover:underline transition-colors"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </motion.div>

        {/* Sections */}
        <div className="space-y-10">
          {SECTIONS.map((section, i) => (
            <motion.section
              key={section.id}
              id={section.id}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.35, delay: i < 4 ? i * 0.05 : 0 }}
              className="scroll-mt-20"
            >
              <h2 className="text-xl font-bold text-gray-900 mb-3">{section.title}</h2>
              <div className="space-y-3">
                {section.content.split('\n\n').map((para, pi) => (
                  <p key={pi} className="text-gray-600 leading-relaxed whitespace-pre-line">
                    {para}
                  </p>
                ))}
              </div>
              {i < SECTIONS.length - 1 && (
                <div className="border-b border-orange-50 mt-10" />
              )}
            </motion.section>
          ))}
        </div>

        {/* Footer links */}
        <div className="mt-16 pt-8 border-t border-orange-100 flex flex-wrap gap-4 text-sm text-gray-400">
          <Link to="/terms" className="hover:text-orange-500 transition-colors">Terms of Service</Link>
          <Link to="/contact" className="hover:text-orange-500 transition-colors">Contact Us</Link>
        </div>
      </div>
    </div>
  );
}
